apiVersion: v1
kind: Service
metadata:
  name: hr-absolute-backend
spec:
  selector:
    app: hr-absolute-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
